### ISSUE TITLE
Configure default retry timeout in top level APIs

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [dgageot/simplelenium#21]
I'd like to make it possible to configure the default timeout once per test instead of in each chain.
Is this something you've attempted before or have thoughts on how you'd like it implemented?

Right now the two places that seem like it should be overridable are SeleniumTest and PageObject.

So far it looks like the default Retry is only used in LazyDomSelector:
![image](https://cloud.githubusercontent.com/assets/2127384/13416547/b4306964-df31-11e5-9508-5034e000844a.png)

My plan is to somehow pass down a duration and timeunit down to LazyDomSelector from SeleniumTest and PageObject for it to use instead of wherever the default retry is used.

Does this sound like something you'd welcome a pull request for?

Thanks!

**Comment by miccheng** [comment]
@dgageot: Could you review this?
