### ISSUE TITLE
Selectbox

### ISSUE THREAD

**Issue by mgohin** [dgageot/simplelenium#3]
Hi,

If I have a select with multiple options and ```<option value="12345">toto</option>``` is selected, I want to check that ```toto``` is selected and ```12345``` is the value selected.

I didn't see any doc or methods about it.

**Comment by dgageot** [comment]
You should write something like this:

```
find("select option").withAttribute("value").equalTo("12345").should().beSelected();
```

or

```
find("select option").withText("toto").should().beSelected();
```

or event use both at the same time:

```
find("select option")
  .withText("toto")
  .withAttribute("value").equalTo("12345")
  .should().beSelected();
```

**Comment by mgohin** [comment]
When I'm trying to use ```.selectByValue("12345")``` it doesn't work, it's waiting then failing

**Comment by dgageot** [comment]
Take a look at src/test/java/net/codestory/simplelenium/SelectTest.java, it does what you want
