### ISSUE TITLE
Javascript errors

### ISSUE THREAD

**Issue by mgohin** [dgageot/simplelenium#4]
Any way to get javascript errors easily with Simplenium ?

I'm struggling with a (angularjs) ngDialog not showing problem in my integration tests and it would be nice to see if js errors occured

**Comment by dgageot** [comment]
Can you see the errors using the `console()` method?

**Comment by mgohin** [comment]
Where does ```console()``` comes from ?

**Comment by dgageot** [comment]
It comes from the `Navigation` interface. So you should have the method on instances of `SeleniumTest`

**Comment by mgohin** [comment]
Here is the ```Navigation``` interface I found, I don't see any ```console``` function

```java
public interface Navigation extends DomElementFinder {
  ThreadLocal<String> baseUrl = new ThreadLocal<>();

  static String getBaseUrl() {
    return baseUrl.get();
  }

  static void setBaseUrl(String url) {
    baseUrl.set(url);
  }

  default PhantomJSDriver driver() {
    return CurrentWebDriver.get();
  }

  default Object executeJavascript(String javascriptCode, Object... args) {
    return driver().executeScript(javascriptCode, args);
  }

  default Navigation goTo(String url) {
    requireNonNull(url, "The url cannot be null");

    URI uri = URI.create(url);
    if (!uri.isAbsolute()) {
      url = getBaseUrl() + url;
    }

    System.out.println("goTo " + url);

    driver().get(url);

    System.out.println(" - current url " + driver().getCurrentUrl());

    return this;
  }

  default Navigation goTo(PageObject page) {
    goTo(page.url());
    return this;
  }```

**Comment by dgageot** [comment]
Can you try upgrading to version 1.34?

**Comment by mgohin** [comment]
Yes, we were using 1.32, I'll try it

**Comment by mgohin** [comment]
In my ```@After``` I look into ```console()``` but it's empty.

When I test myself on the server with the same conditions I have a js error

**Comment by dgageot** [comment]
You are running with phantomjs right?

**Comment by mgohin** [comment]
Yep

**Comment by dgageot** [comment]
So I have no idea...

**Comment by dgageot** [comment]
Can't reproduce
